# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build using dotnet cli'
  inputs:
    command: 'build'
    projects: './src/BooksMgmt.API/BooksMgmt.API.csproj'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './src/BooksMgmt.Domain.Tests/BooksMgmt.Domain.Tests.csproj'
    testRunTitle: 'Unit Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'My-Subscripption1-Pay-As-You-Go(1)(c7401fd2-f8d0-48a2-ac5a-c3ae921545c0)'
    appType: 'webAppLinux'
    appName: BooksMgmtAPI
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|7.0'

